name: Populate Kanban from Markdown

on:
  push:
    paths:
      - "tasks/*.md"

permissions:
  contents: read
  issues: write
  pull-requests: write
  projects: write

jobs:
  create-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install gray-matter @actions/github @actions/core

      - name: Populate Project from Markdown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # 👇 Change these to match your setup
          OWNER: sctgithub              # org or username that owns the Project v2
          PROJECT_NUMBER: 1             # the visible project number in the UI
          STATUS_FIELD_NAME: Status     # the single-select field that powers board columns
          TASKS_DIR: tasks              # folder holding your .md tasks
        run: node .github/scripts/populate-kanban.js
